<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    
	<!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="/img/banner1.jpg" alt="">
            <div class="carousel-caption">
                <h3 class="titulo"><br></h3>
                <h3 class="titulo"><br></h3>
                <p class="subtitulo">30 años fabricando muebles</p>
<!--                 <a class="vinculo">IR A RESTAURANTES</a> -->
            </div>
        </div>
        <div class="item">
            <img src="/img/banner2.jpg" alt="">
            <div class="carousel-caption">
                <h3 class="titulo"><br></h3>
                <h3 class="titulo"><br></h3>
                <p class="subtitulo">Confía en nuestra experiencia</p>
<!--                 <a class="vinculo">IR A AUDITORIOS</a> -->
            </div>
        </div>
        <div class="item">
            <img src="/img/banner3.jpg" alt="">
            <div class="carousel-caption">
                <h3 class="titulo"><br></h3>
                <h3 class="titulo"><br></h3>
                <p class="subtitulo">Diseños personalizados</p>
<!--                 <a class="vinculo">IR A U. EDUCATIVAS</a> -->
            </div>
        </div>
<!--         <div class="item"> -->
<!--             <img src="/img/banner4.jpg" alt=""> -->
<!--             <div class="carousel-caption"> -->
<!--                 <h3 class="titulo">MUEBLES</h3> -->
<!--                 <p class="subtitulo">PARA HOTELES</p> -->
<!--                 <a class="vinculo">IR A HOTELES</a> -->
<!--             </div> -->
<!--         </div> -->
    </div>
    
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Siguiente</span>
    </a>
</div>
