<?php $products=$category[0]->getProducts(); ?>
<img class="img-responsive center-block" alt="" src="<?=$category[0]->getImage() ?>">
<div class="container category-page">
    <div class="row">        
            <h2 class="category-title">
                muebles para
                <span><?=$category[0]->getTitle()?></span>
                <img class="img-responsive center-block" alt="" src="/img/spacer.png">
            </h2>
            <div class="container">
                <div class="products-grid">
                    <?php foreach($products as $product): ?>
                        <div class="product-col">
                            <a href="/producto/<?php echo $product->getSlug(); ?>">

                               <div class="thumb" style="background:url(<?php echo $product->getThumbnail() ?>) bottom center no-repeat;background-size:contain"></div>
                                <?=$product->getTitle() ?>
                            </a>
                        </div>
                    <?php endforeach; ?>
                    
                </div>      
            </div>
    </div>
</div>

<?php
echo $this->render('application/index/categorias');
?>