<!-- <div class="container-fluid contenido-wrap"> -->
<!--     <div class="col-md-3"> -->
<!--         <img class="img-responsive imagenes-categorias" alt="" src="/img/restaurantes1.jpg"> -->
<!--     </div> -->
<!--     <div class="col-md-3"> -->
<!--         <img class="img-responsive imagenes-categorias" alt="" src="/img/restaurantes1.jpg"> -->
<!--     </div> -->
<!--     <div class="col-md-3"> -->
<!--         <img class="img-responsive imagenes-categorias" alt="" src="/img/restaurantes1.jpg"> -->
<!--     </div> -->
<!--     <div class="col-md-3"> -->
<!--         <img class="img-responsive imagenes-categorias" alt="" src="/img/restaurantes1.jpg"> -->
<!--     </div> -->
<!-- </div> -->

<div class="container-fluid categoria-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <img class="img-responsive imagenes-categorias" alt="" src="/img/educacion2.png">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                
                <div class="link-wrap"><a href="<?=$this->url('categoria',['slug'=>'unidades-educativas'])?>" class="btn btn-default" role="button">ver productos</a></div>
            </div>
            <div class="col-md-3">
                <img class="img-responsive imagenes-categorias" alt="" src="/img/hoteles2.png">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                
                <div class="link-wrap"><a href="<?=$this->url('categoria',['slug'=>'hoteles'])?>" class="btn btn-default">ver productos</a></div>
            </div>
            <div class="col-md-3">
                <img class="img-responsive imagenes-categorias" alt="" src="/img/auditorios2.png">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                
                <div class="link-wrap"><a href="<?=$this->url('categoria',['slug'=>'auditorios'])?>" class="btn btn-default">ver productos</a></div>
            </div>
            <div class="col-md-3">
                <img class="img-responsive imagenes-categorias" alt="" src="/img/restaurantes2.png">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                
                <div class="link-wrap"><a href="<?=$this->url('categoria',['slug'=>'restaurantes'])?>" class="btn btn-default">ver productos</a></div>
            </div>
        </div>
    </div>
</div>