<div class="container-fluid container-no-padding">
    <!-- <img style="width:100%;" alt="" src="/img/banner2.jpg"> -->
    <?php 
        //echo '<img style="width:100%;" alt="" src="/img/banner2.jpg">';
        echo $this->render('application/index/carousel');
    ?>
</div>
<?php
// $this->headTitle('Welcome');
//$this->mainMenu()->setActiveItemId('restaurantes');
echo $this->render('application/index/categorias');
?>
<br />
<br />
<br />
<img class="img-responsive center-block" alt="" src="/img/fabricante3.jpg">
<br />
<br />
<img class="img-responsive center-block" alt="" src="/img/fabricante5.jpg">
<br />
<div class="container-fluid text-center">
    <div class="row justify-content-md-center">
        <div class="col-md-3 center-block"></div>
        <div class="col-md-6 center-block">
            <h1 style="font-family: serif;font-weight: bold;">D-Metal</h1>
            <p style="font-size: 17px;">Es una compañía con más de veinte años de experiencia en la fabricación de muebles, constituida para ofrecer a nuestros clientes la más alta calidad y comodidad
                en nuestra amplia gama de modelos y estilos, complaciendo las necesidades y gustos de cada uno.</p>
            <p style="font-size: 17px;">En Inanbesa, nos preocupamos de cada detalle, desde la tecnologíade las soldaduras hasta la atención a nuestros clientes, cuidando la calidad en cada parte 
                de la fabricacíon de nuestros productos, para satisfacer las exigencias del mundo moderno.</p>
            <p style="font-size: 17px;">Con nuestra gama de materiales, colores y tapicería, podemos adaptar nuestros productos a las necesidades de cada cliente, personalizando nuestra producción 
                para cada caso en particular e incluso desarrollando modelos exclusivos.</p>
            <p style="font-size: 17px;">Nos especializamos en muebles para restaurantes, hogar, bares, eventos, oficina, e institutos de enseñanza, entre nuestros principales clientes encontramos 
                universidades, colegios, hospitales, restaurantes, bares, etc.</p>
        </div>
        <div class="col-md-3 center-block"></div>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<img class="img-responsive" alt="" src="/img/fabricante1.jpg">
