<img class="img-responsive center-block" alt="" src="/img/nosotros.png">
<div class="row">
    <div class="col-md-3 center-block"></div>
    <div class="col-md-6 center-block">
        <br />
        <br />
        <h1 class="contenido-titulo">Sobre Nosotros</h1>
        <h1 class="contenido-subtitulo">La Empresa</h1>
        <img width="39" height="9" class="img-responsive center-block" alt="" src="/img/fabricante5.jpg">
        <br />
        <hr>
        <br />
        <br />
        
        <p style="font-size: 17px;">Es una compañía con más de veinte años de experiencia en la fabricación de muebles, constituida para ofrecer a nuestros clientes la más alta calidad y comodidad
            en nuestra amplia gama de modelos y estilos, complaciendo las necesidades y gustos de cada uno.</p>
        <p style="font-size: 17px;">En Inanbesa, nos preocupamos de cada detalle, desde la tecnologíade las soldaduras hasta la atención a nuestros clientes, cuidando la calidad en cada parte 
            de la fabricacíon de nuestros productos, para satisfacer las exigencias del mundo moderno.</p>
        <p style="font-size: 17px;">Con nuestra gama de materiales, colores y tapicería, podemos adaptar nuestros productos a las necesidades de cada cliente, personalizando nuestra producción 
            para cada caso en particular e incluso desarrollando modelos exclusivos.</p>
        <p style="font-size: 17px;">Nos especializamos en muebles para restaurantes, hogar, bares, eventos, oficina, e institutos de enseñanza, entre nuestros principales clientes encontramos 
            universidades, colegios, hospitales, restaurantes, bares, etc.</p>
        
    </div>
    <div class="col-md-3 center-block"></div>
</div>


<br />
<br />
<br />
<img class="img-responsive center-block" alt="" src="/img/fabricante3.jpg">
<br />
<br />
<br />
<br />
<br />
<img class="img-responsive" alt="" src="/img/fabricante1.jpg">
<?php
echo $this->render('application/index/categorias');
?>